spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: AKIAZG7QPCN6YXYYFU4X
    password: BPbuDoNIB7+NMGew6dvLhRlJaeyTciWEZkIVqF3cMX+v
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
