spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: dundung6135@gmail.com
    password: djaakdi1@
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
