spring:
  mail:
    host: email-smtp.ap-northeast-2.amazonaws.com
    port: 465
    username: AKIAZG7QPCN6YXYYFU4X
    password: BPbuDoNIB7+NMGew6dvLhRlJaeyTciWEZkIVqF3cMX+v
    protocol: smtps
    debug: true
    properties.mail.smtp:
      starttls.enable: true
      starttls.required: true
      ssl.enable: true
    properties.mail.smtps:
      auth: true
